- id: '1684175810305'
  alias: Reset inverter max power
  description: If nordpool over 0.8 reset inverter power limit
  trigger:
  - type: monetary
    platform: device
    device_id: f7776f9a9040f3a2f9cdd98af227bbaa
    entity_id: sensor.nordpool_kwh_ee_eur_3_10_02
    domain: sensor
    above: 0.8
  condition:
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: huawei_solar.reset_maximum_feed_grid_power
    data:
      device_id: 0eb5649b85041cc761fe4843117b3c15
  mode: single
- id: '1684175919922'
  alias: Limit inverter power
  description: If nordpool under 0.8 limit inverter power
  trigger:
  - type: monetary
    platform: device
    device_id: f7776f9a9040f3a2f9cdd98af227bbaa
    entity_id: sensor.nordpool_kwh_ee_eur_3_10_02
    domain: sensor
    below: 0.8
  condition:
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: huawei_solar.set_maximum_feed_grid_power_percent
    data:
      power_percentage: 3
      device_id: 0eb5649b85041cc761fe4843117b3c15
  mode: single
